import {QUESTIONS} from './data.js';
import {MT_EXAM,OFFICIAL_QUESTIONS} from './official.js';
const BUILTIN=[...OFFICIAL_QUESTIONS.filter(q=>q.displayMode!=='source-pdf'),...QUESTIONS];
const PENDING_OFFICIAL=OFFICIAL_QUESTIONS.filter(q=>q.displayMode==='source-pdf');
import {validateBank,shuffle,latestErrors,summary} from './core.js';
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='ppmt-v2';let store={attempts:[],favorites:[],custom:[],sessions:[],program:null};
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.attempts)&&Array.isArray(s.favorites)&&Array.isArray(s.sessions)){validateBank(s.custom);store={...s,program:s.program||null};}}catch{setTimeout(()=>toast('Não foi possível ler os dados locais. Importe um backup, se tiver.'),100)}
function localDay(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function ensureProgram(){if(!store.program||typeof store.program!=='object')store.program={startDate:localDay(),completed:{},xp:0};if(!store.program.startDate)store.program.startDate=localDay();if(!store.program.completed)store.program.completed={};if(!Number.isFinite(store.program.xp))store.program.xp=0}
ensureProgram();
let tab='inicio',filter={search:'',subject:'',kind:'prova'},index=0,selection=null,answered=false,queue=[],run=null,examResult=null;
const pages=[['inicio','◫','Hoje'],['missao','◆','Missão do dia'],['desempenho','▥','Meu progresso'],['provas','▧','Acervo de provas'],['materias','▦','Matérias'],['questoes','▤','Banco'],['simulados','◷','Simulados'],['erros','↺','Erros'],['favoritos','☆','Favoritos'],['dados','⚙','Meus dados']];
const bank=()=>[...BUILTIN,...store.custom];
function save(){try{localStorage.setItem(KEY,JSON.stringify(store));return true}catch{toast('Não foi possível salvar neste navegador. Exporte um backup.');return false}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200)}
function title(t,d){return `<h1>${t}</h1><p class="muted">${d}</p>`}
function stats(){const s=summary(store.attempts);return `<div class="stats">${[['Questões respondidas',s.total,'tentativas registradas'],['Aproveitamento',s.rate+'%','em todas as tentativas'],['Para revisar',latestErrors(store.attempts).size,'última resposta incorreta'],['Simulados feitos',store.sessions.length,'finalizados']].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}</div>`}
function subjects(){return [...new Set(bank().map(q=>q.subject))]}
function progress(){return subjects().map(s=>{const ids=new Set(bank().filter(q=>q.subject===s).map(q=>q.id)),r=summary(store.attempts.filter(a=>ids.has(a.id)));return `<div class="subject"><div class="row"><span>${esc(s)}</span><span class="muted">${r.total?r.rate+'%':'Sem respostas'}</span></div><div class="track"><i style="width:${r.rate}%"></i></div></div>`}).join('')}
function daysBetween(a,b){const [ay,am,ad]=a.split('-').map(Number),[by,bm,bd]=b.split('-').map(Number);return Math.floor((Date.UTC(by,bm-1,bd)-Date.UTC(ay,am-1,ad))/86400000)}
function programDay(){return Math.max(1,Math.min(90,daysBetween(store.program.startDate,localDay())+1))}
function todayDone(){return !!store.program.completed[localDay()]}
function streak(){let n=0,d=new Date();for(;;){const k=localDay(d);if(!store.program.completed[k])break;n++;d.setDate(d.getDate()-1)}return n}
function rankName(){const x=store.program.xp||0;if(x>=5000)return'ELITE';if(x>=3000)return'OPERACIONAL';if(x>=1500)return'AGENTE';if(x>=500)return'ALUNO';return'RECRUTA'}
function realBank(){return bank().filter(q=>q.origin==='prova')}
function subjectPerformance(name){const ids=new Set(realBank().filter(q=>q.subject===name).map(q=>q.id));return summary(store.attempts.filter(a=>ids.has(a.id)))}
function weakestSubject(){const ss=[...new Set(realBank().map(q=>q.subject))];return ss.map(name=>({name,s:subjectPerformance(name)})).sort((a,b)=>{const ar=a.s.total?a.s.rate:-1,br=b.s.total?b.s.rate:-1;return ar-br||a.s.total-b.s.total})[0]?.name||ss[0]}
function rotateSubject(offset=0){const ss=[...new Set(realBank().map(q=>q.subject))];return ss[(programDay()-1+offset)%ss.length]}
function missionSpec(){const day=programDay(),cycle=(day-1)%7,weak=weakestSubject(),s1=rotateSubject(0),s2=rotateSubject(3);const plans=[
 {type:'subject',title:'Foco de matéria',desc:`Domine ${s1}. Hoje o app escolheu essa disciplina para você.`,subject:s1,count:10,minutes:18},
 {type:'mixed',title:'Simulado dirigido',desc:'Mistura controlada de matérias para treinar troca rápida de raciocínio.',count:20,minutes:30},
 {type:'errors',title:'Correção de rota',desc:'Hoje é dia de atacar seus erros recentes. Se faltarem erros, o app completa com seu ponto fraco.',subject:weak,count:12,minutes:22},
 {type:'dual',title:'Dupla de matérias',desc:`${s1} + ${s2}. O treino de hoje alterna duas disciplinas.`,subjects:[s1,s2],count:16,minutes:28},
 {type:'mixed',title:'Simulado de pressão',desc:'Ritmo mais forte e menos tempo por questão. Sem escolher matéria.',count:25,minutes:35},
 {type:'weak',title:'Ponto fraco',desc:`Seu desempenho indica prioridade em ${weak}. Hoje a missão é recuperar essa matéria.`,subject:weak,count:15,minutes:25},
 {type:'full',title:'Prova semanal',desc:'Fechamento da semana: prova real completa, em ordem, como no dia do concurso.',count:realBank().length,minutes:270}
];return {...plans[cycle],day}}
function missionQuestions(spec){const all=realBank();let qs=[];if(spec.type==='subject'||spec.type==='weak')qs=all.filter(q=>q.subject===spec.subject);else if(spec.type==='dual')qs=all.filter(q=>spec.subjects.includes(q.subject));else if(spec.type==='errors'){const ids=latestErrors(store.attempts);qs=all.filter(q=>ids.has(q.id));if(qs.length<spec.count){const fill=all.filter(q=>q.subject===spec.subject&&!qs.includes(q));qs=[...qs,...fill]}}else qs=all.slice();if(spec.type==='full')return qs.slice().sort((a,b)=>Number(a.source?.number||0)-Number(b.source?.number||0));return shuffle(qs).slice(0,Math.min(spec.count,qs.length))}
function missionHeader(){const d=programDay(),pct=Math.round((d-1)/90*100);return `<section class="mission-status"><div><span class="eyebrow">PROJETO APROVAÇÃO • 90 DIAS</span><h2>Dia ${d} de 90</h2><div class="track"><i style="width:${pct}%"></i></div></div><div class="mission-kpis"><span><b>${streak()}</b>dias seguidos</span><span><b>${store.program.xp}</b>XP</span><span><b>${rankName()}</b>patente</span></div></section>`}
function renderMission(){
 if(run&&run.originTab==='missao'){showExamQuestion();return}
 const spec=missionSpec(),done=todayDone(),last=store.program.completed[localDay()];
 $('#content').innerHTML=missionHeader()+`<section class="card daily-mission ${done?'done':''}"><div class="mission-badge">${done?'✓':'◆'}</div><div class="eyebrow">${done?'MISSÃO CONCLUÍDA':'MISSÃO DO DIA'}</div><h1>${esc(spec.title)}</h1><p>${esc(spec.desc)}</p><div class="mission-facts"><span><b>${spec.count}</b> questões</span><span><b>${spec.minutes}</b> min</span><span><b>+${100}</b> XP base</span></div>${done?`<div class="mission-result"><b>${last.correct}/${last.total} acertos</b><span>${last.rate}% de aproveitamento</span></div><p class="muted">A próxima missão será liberada amanhã. Você pode consultar seu progresso enquanto isso.</p>`:`<button id="startMission" class="primary mission-cta">INICIAR MISSÃO →</button><p class="muted">As áreas de treino ficam bloqueadas até você concluir a missão de hoje.</p>`}</section><section class="card spaced"><div class="row"><h2>Como funciona</h2><span class="tag">AUTOMÁTICO</span></div><p class="muted">O aplicativo alterna matérias, simulados, revisão de erros, ponto fraco e prova completa. Você não precisa decidir o que estudar: apenas cumprir a missão liberada hoje.</p></section>`;
 if(!done)$('#startMission').onclick=()=>startMission(spec)
}
function startMission(spec=missionSpec()){const qs=missionQuestions(spec);if(!qs.length){toast('Ainda não há questões suficientes para esta missão.');return}examResult=null;run={questions:qs,answers:Object.create(null),index:0,deadline:Date.now()+spec.minutes*60000,originTab:'missao',label:spec.title,missionDay:spec.day};showExamQuestion()}
function lockStudy(dest){return !todayDone()&&['materias','provas','questoes','simulados','erros','favoritos'].includes(dest)}
function renderSubjects(){
 const real=bank().filter(q=>q.origin==='prova');
 const groups=[...new Set(real.map(q=>q.subject))].map(name=>({name,count:real.filter(q=>q.subject===name).length}));
 $('#content').innerHTML=title('Estudar por matéria','Escolha uma disciplina e responda apenas questões reais daquela matéria, misturando as provas que forem adicionadas ao acervo.')+`<div class="subject-grid">${groups.map(g=>`<section class="card subject-card"><div class="subject-check">✓</div><div><h2>${esc(g.name)}</h2><p class="muted">${g.count} questão${g.count===1?'':'ões'} disponível${g.count===1?'':'is'}</p><button class="primary subject-start" data-subject="${esc(g.name)}">Responder →</button></div></section>`).join('')}</div><div class="notice">À medida que adicionarmos provas de outros concursos de Polícia Penal, as questões entram automaticamente na matéria correspondente.</div>`;
 document.querySelectorAll('.subject-start').forEach(b=>b.onclick=()=>{filter={search:'',subject:b.dataset.subject,kind:'prova'};location.hash='questoes'});
}
function navigate(){let dest=location.hash.slice(1)||'inicio';if(lockStudy(dest)){toast('Conclua a missão do dia para liberar o treino livre.');dest='missao';if(location.hash!=='#missao'){location.hash='missao';return}}if(run&&dest!==(run.originTab||'simulados')){if(!confirm('Sair desta missão? As respostas desta sessão não serão salvas.')){location.hash=run.originTab||'missao';return}run=null}tab=pages.some(p=>p[0]===dest)?dest:'inicio';index=0;selection=null;answered=false;render()}
window.addEventListener('hashchange',navigate);
function render(){
 $('#nav').innerHTML=pages.map(([id,icon,name])=>{const locked=lockStudy(id);return `<a href="#${locked?'missao':id}" class="${tab===id?'active':''} ${locked?'locked':''}" ${tab===id?'aria-current="page"':''}><span class="navicon">${locked?'🔒':icon}</span>${name}</a>`}).join('');
 const c=$('#content');
 if(tab==='inicio'){const spec=missionSpec(),done=todayDone();c.innerHTML=missionHeader()+`<section class="hero mission-hero"><div><div class="eyebrow">${done?'MISSÃO DE HOJE CONCLUÍDA':'SUA ORDEM DE HOJE'}</div><h2>${done?'MISSÃO CUMPRIDA.':esc(spec.title)}</h2><p class="muted">${done?'Volte amanhã para receber a próxima etapa do Projeto Aprovação.':esc(spec.desc)}</p><a class="button primary" href="#missao">${done?'Ver resultado →':'Cumprir missão →'}</a><div class="operation-strip"><span>DIA ${programDay()}/90</span><span>${rankName()}</span><span>${store.program.xp} XP</span></div></div><div class="hero-art" aria-hidden="true"><img src="./icon.svg" alt=""></div></section>`+stats()+`<div class="columns"><section class="card"><div class="row"><h2>Seu desempenho por matéria</h2><span class="tag">ACERTOS</span></div>${progress()}</section><section class="card"><span class="pill">MODO GUIADO</span><h2 class="spaced">O app decide o treino.</h2><p class="muted">Cada dia tem uma missão diferente. Treino livre só é liberado depois que você cumprir a etapa obrigatória do dia.</p><a class="button secondary" href="#missao">Ver missão do dia →</a></section></div>`}
 if(tab==='missao')renderMission();
 if(tab==='materias')renderSubjects();
 if(['questoes','erros','favoritos'].includes(tab))renderPractice();
 if(tab==='simulados')renderExam();
 if(tab==='provas')renderArchive();
 if(tab==='desempenho'){c.innerHTML=title('Cada resposta conta.','Indicadores calculados com suas tentativas neste navegador.')+stats()+`<div class="columns"><section class="card"><h2>Por matéria</h2>${progress()}</section><section class="card"><h2>Últimos simulados</h2>${store.sessions.length?store.sessions.slice(-8).reverse().map(s=>`<div class="list-item row"><span>${new Date(s.at).toLocaleDateString('pt-BR')} • ${s.total} questões</span><b>${s.correct}/${s.total} acertos</b></div>`).join(''):'<p class="muted">Seus resultados aparecerão aqui após o primeiro simulado.</p>'}</section></div>`;}
 if(tab==='dados')renderData();
}
function pool(){const errors=latestErrors(store.attempts);return bank().filter(q=>(tab!=='erros'||errors.has(q.id))&&(tab!=='favoritos'||store.favorites.includes(q.id))&&(!filter.subject||q.subject===filter.subject)&&(!filter.kind||q.origin===filter.kind)&&(!filter.search||(q.statement+' '+q.topic).toLocaleLowerCase('pt-BR').includes(filter.search.toLocaleLowerCase('pt-BR'))));}
function renderPractice(){
 const heading=tab==='erros'?['Revisar é avançar.','Questões cuja última resposta registrada foi incorreta.']:tab==='favoritos'?['Seu caderno de favoritos.','Guarde questões para retomar depois.']:['Banco de questões','Questões completas para responder dentro do aplicativo, com enunciado, alternativas, gabarito e fonte oficial para conferência.'];
 $('#content').innerHTML=title(...heading)+`<div class="filters"><label>Buscar número, enunciado ou assunto<input id="search" placeholder="Ex.: questão 21 ou constitucional" value="${esc(filter.search)}"></label><label>Matéria<select id="subject"><option value="">Todas as matérias</option>${subjects().map(s=>`<option ${s===filter.subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Origem<select id="kind"><option value="">Todas</option><option value="autoral" ${filter.kind==='autoral'?'selected':''}>Autorais</option><option value="prova" ${filter.kind==='prova'?'selected':''}>Provas reais</option></select></label></div><p class="muted filter-note">Aqui só entram questões já transcritas e conferidas. O PDF original fica apenas como fonte de conferência; questões ainda não transcritas não entram no treino.</p><div id="questionArea"></div>`;
 for(const key of ['search','subject','kind'])$('#'+key).addEventListener(key==='search'?'input':'change',e=>{filter[key]=e.target.value;index=0;answered=false;selection=null;queue=pool();showQuestion()});
 queue=pool();showQuestion();
}
function showQuestion(){
 const area=$('#questionArea');if(!queue.length){area.innerHTML='<div class="card empty"><h2>Nenhuma questão por aqui.</h2><p>Altere os filtros ou comece uma nova sessão de estudo.</p><button id="clearFilters">Limpar filtros</button></div>';$('#clearFilters').onclick=()=>{filter={search:'',subject:'',kind:'prova'};renderPractice()};return}
 index=Math.min(index,queue.length-1);const q=queue[index];area.innerHTML=questionHTML(q,false)+`<div class="actions spaced"><button id="prev" ${index===0?'disabled':''}>← Anterior</button><button id="respond" class="primary" ${selection===null||answered?'disabled':''}>Conferir resposta</button><button id="next" ${index===queue.length-1?'disabled':''}>Próxima →</button><span class="muted">${index+1} de ${queue.length}</span></div>`;
 bindOptions(q,()=>showQuestion());$('#favorite').onclick=()=>{toggleFavorite(q.id);showQuestion()};
 $('#respond').onclick=()=>{if(selection===null||answered)return;answered=true;store.attempts.push({id:q.id,selected:selection,correct:selection===q.answer,at:new Date().toISOString(),mode:'practice'});save();showQuestion()};
 for(const [id,delta] of [['prev',-1],['next',1]])$('#'+id).onclick=()=>{index+=delta;selection=null;answered=false;showQuestion()};
}
function questionHTML(q,exam){const inline=q.displayMode!=='source-pdf';return `<article class="card question"><div class="row"><div class="meta">${esc(q.subject)} / ${esc(q.topic)}<br>${q.origin==='autoral'?'AUTORAL • DEMONSTRAÇÃO':esc(q.source.board)+' • '+esc(q.source.year)+' • '+esc(q.source.exam)+' • Q'+esc(q.source.number)+(q.source.version?' • Caderno '+esc(q.source.version):'')}</div>${!exam?`<button id="favorite" class="secondary" aria-label="${store.favorites.includes(q.id)?'Remover dos':'Adicionar aos'} favoritos">${store.favorites.includes(q.id)?'★ Salva':'☆ Salvar'}</button>`:''}</div><p class="statement">${esc(q.statement)}</p>${inline?'':referenceReader(q)}<div class="options" role="group" aria-label="Alternativas">${q.options.map((o,i)=>`<button class="option ${selection===i?'selected':''} ${answered&&!exam?(i===q.answer?'correct':i===selection?'wrong':''):''}" data-option="${i}" aria-label="Alternativa ${String.fromCharCode(65+i)}" aria-pressed="${selection===i}" ${answered&&!exam?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${inline?esc(o):'Alternativa '+String.fromCharCode(65+i)}</span></button>`).join('')}</div>${q.origin==='prova'&&inline?`<div class="question-source"><a href="${esc(q.source.examUrl)}#page=${Number(q.source.page)||1}" target="_blank" rel="noopener noreferrer">Ver questão na prova original ↗</a></div>`:''}${answered&&!exam?feedback(q,selection):''}</article>`}
function feedback(q,selected){return `<div class="feedback ${selected!==q.answer?'bad':''}" role="status"><b>${selected===q.answer?'Resposta correta!':selected===undefined?'Não respondida.':'Ainda não foi dessa vez.'} Gabarito: ${String.fromCharCode(65+q.answer)}.</b><p>${esc(q.explanation)}</p>${q.origin==='prova'?`<a href="${esc(q.source.examUrl)}" target="_blank" rel="noopener noreferrer">Consultar prova</a> · <a href="${esc(q.source.answerUrl)}${q.source.answerPage?'#page='+Number(q.source.answerPage):''}" target="_blank" rel="noopener noreferrer">Consultar gabarito</a><p>${q.displayMode==='source-pdf'?'Conferência documental do gabarito histórico':'Revisão declarada na importação'}: ${esc(q.source.reviewedAt)}.</p>`:'<small>Questão autoral para demonstração da plataforma.</small>'}</div>`}
function bindOptions(q,fn){document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{if(answered&&!run)return;selection=Number(b.dataset.option);if(run)run.answers[q.id]=selection;document.querySelectorAll('[data-option]').forEach(el=>{const yes=Number(el.dataset.option)===selection;el.classList.toggle('selected',yes);el.setAttribute('aria-pressed',String(yes))});if($('#respond'))$('#respond').disabled=false;if($('#answeredCount'))$('#answeredCount').textContent=Object.keys(run.answers).length})}
function toggleFavorite(id){store.favorites=store.favorites.includes(id)?store.favorites.filter(x=>x!==id):[...store.favorites,id];save()}
function renderExam(){
 if(run){showExamQuestion();return}
 if(examResult){const r=examResult;$('#content').innerHTML=title('Treino concluído.','Confira o resultado e revise cada resposta.')+`<div class="card"><span class="result-score">${Math.round(r.correct/r.questions.length*100)}%</span><p>${r.correct} de ${r.questions.length} acertos • ${r.unanswered} sem resposta</p><button id="newExam" class="primary">Novo simulado</button></div>`+r.questions.map((q,i)=>`<section class="card spaced"><h3>${i+1}. ${esc(q.statement)}</h3><p class="muted">Sua resposta: ${r.answers[q.id]===undefined?'Não respondida':esc(q.options[r.answers[q.id]])}</p>${feedback(q,r.answers[q.id])}</section>`).join('');$('#newExam').onclick=()=>{examResult=null;renderExam()};return}
 $('#content').innerHTML=title('Simule o dia da prova.','Questões aleatórias, tempo definido por você e correção ao finalizar.')+`<section class="card"><h2>Monte seu treino</h2><div class="filters exam-filters"><label>Origem<select id="examOrigin"><option value="prova">Provas reais de MT</option><option value="autoral">Treino autoral</option><option value="">Todas</option></select></label><label>Matéria<select id="examSubject"><option value="">Todas as matérias</option>${subjects().map(s=>`<option>${esc(s)}</option>`).join('')}</select></label><label>Quantidade<input id="examCount" type="number" min="1" max="${bank().length}" value="10"></label><label>Tempo em minutos<input id="examTime" type="number" min="1" max="180" value="20"></label></div><p class="muted" id="available"></p><button id="startExam" class="primary">Iniciar simulado →</button><div class="notice">Treino livre: todas as questões valem um acerto, sem os pesos da prova original. Anuladas excluídas. A fonte oficial pode exigir internet; o gabarito jurídico é histórico, sem revisão de vigência. A sessão em andamento não é recuperada ao fechar a página.</div></section>`;
 const examPool=()=>bank().filter(q=>(!$('#examSubject').value||q.subject===$('#examSubject').value)&&(!$('#examOrigin').value||q.origin===$('#examOrigin').value));const update=()=>{const n=examPool().length;$('#examCount').max=n;if(Number($('#examCount').value)>n)$('#examCount').value=n;$('#available').textContent=`${n} questões disponíveis neste recorte.`};$('#examSubject').onchange=update;$('#examOrigin').onchange=update;update();
 $('#startExam').onclick=()=>{const count=Number($('#examCount').value),minutes=Number($('#examTime').value),qs=examPool();if(!Number.isInteger(count)||count<1||count>qs.length||!Number.isInteger(minutes)||minutes<1||minutes>180){toast('Confira a quantidade e o tempo do simulado.');return}run={questions:shuffle(qs).slice(0,count),answers:Object.create(null),index:0,deadline:Date.now()+minutes*60000,originTab:'simulados',label:'Simulado'};showExamQuestion()};
}
function showExamQuestion(){const q=run.questions[run.index];selection=run.answers[q.id]??null;answered=false;$('#content').innerHTML=`<div class="row"><h1>${esc(run.label||'Simulado')} em andamento</h1><span class="timer" id="timer"></span></div><p class="muted">Questão ${run.index+1} de ${run.questions.length} • <span id="answeredCount">${Object.keys(run.answers).length}</span> respondidas</p>`+questionHTML(q,true)+`<div class="actions spaced"><button id="examPrev" ${run.index===0?'disabled':''}>← Anterior</button><button id="examNext" ${run.index===run.questions.length-1?'disabled':''}>Próxima →</button><button id="finish" class="primary">Finalizar simulado</button></div>`;bindOptions(q,showExamQuestion);$('#examPrev').onclick=()=>{run.index--;showExamQuestion()};$('#examNext').onclick=()=>{run.index++;showExamQuestion()};$('#finish').onclick=()=>{const missing=run.questions.length-Object.keys(run.answers).length;if(confirm(missing?`Faltam ${missing} respostas. Finalizar mesmo assim?`:'Finalizar e conferir o gabarito?'))finishExam()};tick()}
function tick(){if(!run)return;const secs=Math.max(0,Math.ceil((run.deadline-Date.now())/1000));if($('#timer'))$('#timer').textContent=`${Math.floor(secs/60).toString().padStart(2,'0')}:${(secs%60).toString().padStart(2,'0')}`;if(!secs)finishExam()}
setInterval(tick,1000);
function finishExam(){if(!run)return;const r=run;run=null;const at=new Date().toISOString();let correct=0,unanswered=0;for(const q of r.questions){const selected=r.answers[q.id];if(selected===q.answer)correct++;if(selected===undefined)unanswered++;store.attempts.push({id:q.id,selected:selected??null,correct:selected===q.answer,at,mode:r.originTab==='missao'?'mission':'exam'})}store.sessions.push({at,total:r.questions.length,correct,mode:r.originTab||'simulados'});if(r.originTab==='missao'){const rate=Math.round(correct/r.questions.length*100),xp=100+correct*5;store.program.completed[localDay()]={at,total:r.questions.length,correct,rate,day:r.missionDay,xp};store.program.xp+=xp}save();examResult={...r,correct,unanswered};if(r.originTab==='missao')renderMission();else if(r.originTab==='provas')renderArchive();else renderExam()}
window.addEventListener('beforeunload',e=>{if(run){e.preventDefault();e.returnValue=''}});
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function renderData(){
 $('#content').innerHTML=title('Seu estudo, seus dados.','O progresso fica salvo neste navegador. Faça backup para levar a outro aparelho.')+`<div class="columns"><section class="card"><h2>Backup do progresso</h2><p class="muted">Inclui respostas, favoritos, simulados e questões importadas. Não há conta nem sincronização na nuvem nesta versão.</p><button id="export" class="primary">Exportar backup</button><label class="spaced">Restaurar backup (.json)<input id="restore" type="file" accept=".json,application/json"></label><p class="muted">A restauração substitui os dados atuais após sua confirmação.</p></section><section class="card"><h2>Adicionar questões</h2><p class="muted">Importe um JSON no formato do projeto. Questões de provas exigem links da prova e do gabarito. A importação é local e não publica para outros usuários.</p><button id="template">Baixar modelo JSON</button><label class="spaced">Importar questões (.json)<input id="import" type="file" accept=".json,application/json"></label><p class="muted">${store.custom.length} questões importadas.</p></section></div><div class="notice">Limpar os dados do navegador pode apagar o progresso. Não armazene senhas ou dados pessoais nos arquivos de questões.</div>`;
 $('#export').onclick=()=>download('pp-mt-backup.json',{version:2,data:store});$('#template').onclick=()=>download('modelo-questoes.json',[{...QUESTIONS[0],id:'minha-questao-001'}]);
 $('#import').onchange=async e=>{try{const list=validateBank(await readFile(e.target.files[0]));const ids=new Set(bank().map(q=>q.id));if(list.some(q=>ids.has(q.id)))throw Error('Já existe uma questão com um dos IDs. Use IDs novos.');if(store.custom.length+list.length>5000)throw Error('Limite local de 5.000 questões importadas.');store.custom.push(...list);save();toast(`${list.length} questões importadas.`);renderData()}catch(err){toast(err.message)}};
 $('#restore').onchange=async e=>{try{const b=await readFile(e.target.files[0]),s=b.data;if(b.version!==2||!s||!Array.isArray(s.attempts)||!Array.isArray(s.favorites)||!Array.isArray(s.sessions))throw Error('Backup inválido.');validateBank(s.custom);const combined=[...BUILTIN,...s.custom],ids=new Set(combined.map(q=>q.id));if(ids.size!==combined.length)throw Error('IDs repetidos no backup.');if(s.attempts.some(a=>!a||!ids.has(a.id)||typeof a.correct!=='boolean'||!Number.isFinite(Date.parse(a.at))||!(a.selected===null||Number.isInteger(a.selected)&&a.selected>=0&&a.selected<combined.find(q=>q.id===a.id).options.length))||s.favorites.some(id=>!ids.has(id))||s.sessions.some(x=>!x||!Number.isFinite(Date.parse(x.at))||!Number.isInteger(x.total)||x.total<1||!Number.isInteger(x.correct)||x.correct<0||x.correct>x.total))throw Error('O backup contém registros inválidos.');if(confirm('Substituir todo o progresso atual por este backup?')){store={attempts:s.attempts,favorites:[...new Set(s.favorites)],sessions:s.sessions,custom:s.custom,program:s.program||{startDate:localDay(),completed:{},xp:0}};ensureProgram();save();toast('Backup restaurado.');renderData()}}catch(err){toast(err.message)}};
}
async function readFile(f){if(!f)throw Error('Selecione um arquivo.');if(f.size>10*1024*1024)throw Error('O arquivo deve ter até 10 MB.');try{return JSON.parse(await f.text())}catch{throw Error('Não foi possível ler o JSON.')}}

function referenceReader(q){if(q.displayMode!=='source-pdf')return '';const page=Number(q.source.page)||1;return `<section class="source-reader pending-transcription"><p><b>Transcrição pendente.</b> Esta questão ainda está no formato antigo. A nova versão do banco mostrará o enunciado e as alternativas diretamente aqui.</p><a class="button secondary" href="${esc(q.source.examUrl)}#page=${page}" target="_blank" rel="noopener noreferrer">Ver questão na prova original ↗</a></section>`}
function renderArchive(){
 if(run&&run.originTab==='provas'){showExamQuestion();return}
 if(examResult&&examResult.originTab==='provas'){const r=examResult;$('#content').innerHTML=title('Prova concluída.','Resultado da prova completa.')+`<div class="card"><span class="result-score">${Math.round(r.correct/r.questions.length*100)}%</span><p>${r.correct} de ${r.questions.length} acertos • ${r.unanswered} sem resposta</p><button id="redoFullExam" class="primary">Refazer prova completa</button></div>`;$('#redoFullExam').onclick=()=>{examResult=null;renderArchive()};return}
 const e=MT_EXAM;$('#content').innerHTML=title('Provas de Mato Grosso','Caderno original, identificação da versão e gabarito definitivo da banca.')+`<section class="card archive-card"><div class="archive-head"><img class="archive-seal" src="./icon.svg" alt="Escudo do preparatório PP MT"><div><div class="eyebrow">ACERVO DE PROVAS / MATO GROSSO</div><h2>Agente Penitenciário · SEJUDH/MT</h2><span class="muted">IBADE · Edital 001/2016 · Prova aplicada em ${e.date}</span></div></div><div class="exam-facts"><div><b>S05 T</b><small>Caderno cadastrado</small></div><div><b>60</b><small>Questões na prova</small></div><div><b>57</b><small>Válidas para treinar</small></div><div><b>3</b><small>Anuladas, fora do treino</small></div></div><p class="muted">O objetivo do banco é resolver tudo dentro do aplicativo: enunciado e alternativas completos. O PDF original fica apenas como fonte de conferência. As questões ainda pendentes de transcrição não entram no treino.</p><div class="source-links"><button class="primary" id="fullOfficial">Responder prova completa →</button><button class="secondary" id="trainOfficial">Estudar questões desta prova →</button><a class="button secondary" href="${e.examUrl}" target="_blank" rel="noopener noreferrer">Prova original ↗</a><a class="button secondary" href="${e.answerUrl}#page=13" target="_blank" rel="noopener noreferrer">Gabarito final ↗</a><a class="button secondary" href="${e.landingUrl}" target="_blank" rel="noopener noreferrer">Página da banca ↗</a></div><div class="notice warning-historical"><b>Acervo histórico de 2017.</b> As questões 16, 41 e 56 foram anuladas e não entram no treino nem nas estatísticas. Respostas jurídicas refletem o gabarito da época; não houve revisão de vigência legislativa. Este material não define o conteúdo de um próximo edital.</div><h3>Matérias do caderno</h3><div class="exam-reference-list">${e.sections.map(x=>`<div>${esc(x.subject)} · Q${x.from}–${x.to}</div>`).join('')}</div><details class="source-reader"><summary>Consultar o caderno completo nesta tela</summary><iframe class="pdf-view" src="${e.examUrl}#page=1" title="Caderno oficial S05 T completo" loading="lazy" referrerpolicy="no-referrer"></iframe></details><p class="source-note">Conferência documental: 07/10/2026 (UTC). Os PDFs são carregados diretamente da IBADE. Leitura integrada depende do navegador; os botões abrem o documento separadamente.</p></section>`;$('#trainOfficial').onclick=()=>{filter={search:'',subject:'',kind:'prova'};location.hash='questoes'};$('#fullOfficial').onclick=()=>{const qs=OFFICIAL_QUESTIONS.filter(q=>q.displayMode!=='source-pdf').slice().sort((a,b)=>Number(a.source.number)-Number(b.source.number));examResult=null;run={questions:qs,answers:Object.create(null),index:0,deadline:Date.now()+270*60000,originTab:'provas',label:'Prova completa'};showExamQuestion()}}

if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
navigate();
