import {QUESTIONS} from './data.js';
import {validateBank,shuffle,latestErrors,summary} from './core.js';
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='ppmt-v2';let store={attempts:[],favorites:[],custom:[],sessions:[]};
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.attempts)&&Array.isArray(s.favorites)&&Array.isArray(s.sessions)){validateBank(s.custom);store=s;}}catch{setTimeout(()=>toast('Não foi possível ler os dados locais. Importe um backup, se tiver.'),100)}
let tab='inicio',filter={search:'',subject:'',kind:''},index=0,selection=null,answered=false,queue=[],run=null,examResult=null;
const pages=[['inicio','◫','Visão geral'],['questoes','▤','Questões'],['simulados','◷','Simulados'],['erros','↺','Revisar erros'],['favoritos','☆','Favoritos'],['desempenho','▥','Desempenho'],['dados','⚙','Meus dados']];
const bank=()=>[...QUESTIONS,...store.custom];
function save(){try{localStorage.setItem(KEY,JSON.stringify(store));return true}catch{toast('Não foi possível salvar neste navegador. Exporte um backup.');return false}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200)}
function title(t,d){return `<h1>${t}</h1><p class="muted">${d}</p>`}
function stats(){const s=summary(store.attempts);return `<div class="stats">${[['Questões respondidas',s.total,'tentativas registradas'],['Aproveitamento',s.rate+'%','em todas as tentativas'],['Para revisar',latestErrors(store.attempts).size,'última resposta incorreta'],['Simulados feitos',store.sessions.length,'finalizados']].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}</div>`}
function subjects(){return [...new Set(bank().map(q=>q.subject))]}
function progress(){return subjects().map(s=>{const ids=new Set(bank().filter(q=>q.subject===s).map(q=>q.id)),r=summary(store.attempts.filter(a=>ids.has(a.id)));return `<div class="subject"><div class="row"><span>${esc(s)}</span><span class="muted">${r.total?r.rate+'%':'Sem respostas'}</span></div><div class="track"><i style="width:${r.rate}%"></i></div></div>`}).join('')}
function navigate(){const dest=location.hash.slice(1)||'inicio';if(run&&dest!=='simulados'){if(!confirm('Sair do simulado? As respostas desta sessão não serão salvas.')){location.hash='simulados';return}run=null}tab=pages.some(p=>p[0]===dest)?dest:'inicio';index=0;selection=null;answered=false;render()}
window.addEventListener('hashchange',navigate);
function render(){
 $('#nav').innerHTML=pages.map(([id,icon,name])=>`<a href="#${id}" class="${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}><span class="navicon">${icon}</span>${name}</a>`).join('');
 const c=$('#content');
 if(tab==='inicio'){c.innerHTML=title('Seu próximo passo começa aqui.','Organize o treino. Entenda seus erros. Construa constância.')+`<section class="hero"><div><div class="eyebrow">OBJETIVO • POLÍCIA PENAL DE MATO GROSSO</div><h2>Foco no estudo.<br>Um acerto de cada vez.</h2><p class="muted">Um espaço para resolver questões, testar seus conhecimentos e acompanhar sua evolução.</p><a class="button primary" href="#questoes">Começar a praticar →</a></div><div class="hero-art" aria-hidden="true">MT</div></section>`+stats()+`<div class="columns"><section class="card"><div class="row"><h2>Seu desempenho por matéria</h2><span class="tag">ACERTOS</span></div>${progress()}</section><section class="card"><span class="pill">TREINO RÁPIDO</span><h2 class="spaced">Teste seu ritmo</h2><p class="muted">Monte uma sessão com as questões disponíveis. O gabarito aparece ao finalizar.</p><a class="button secondary" href="#simulados">Montar simulado →</a><div class="notice">${QUESTIONS.length} questões autorais de demonstração. Matérias jurídicas e questões reais ainda serão adicionadas após conferência das fontes e do edital.</div></section></div>`;}
 if(['questoes','erros','favoritos'].includes(tab))renderPractice();
 if(tab==='simulados')renderExam();
 if(tab==='desempenho'){c.innerHTML=title('Cada resposta conta.','Indicadores calculados com suas tentativas neste navegador.')+stats()+`<div class="columns"><section class="card"><h2>Por matéria</h2>${progress()}</section><section class="card"><h2>Últimos simulados</h2>${store.sessions.length?store.sessions.slice(-8).reverse().map(s=>`<div class="list-item row"><span>${new Date(s.at).toLocaleDateString('pt-BR')} • ${s.total} questões</span><b>${s.correct}/${s.total} acertos</b></div>`).join(''):'<p class="muted">Seus resultados aparecerão aqui após o primeiro simulado.</p>'}</section></div>`;}
 if(tab==='dados')renderData();
}
function pool(){const errors=latestErrors(store.attempts);return bank().filter(q=>(tab!=='erros'||errors.has(q.id))&&(tab!=='favoritos'||store.favorites.includes(q.id))&&(!filter.subject||q.subject===filter.subject)&&(!filter.kind||q.origin===filter.kind)&&(!filter.search||(q.statement+' '+q.topic).toLocaleLowerCase('pt-BR').includes(filter.search.toLocaleLowerCase('pt-BR'))));}
function renderPractice(){
 const heading=tab==='erros'?['Revisar é avançar.','Questões cuja última resposta registrada foi incorreta.']:tab==='favoritos'?['Seu caderno de favoritos.','Guarde questões para retomar depois.']:['Banco de questões','Escolha a matéria e avance no seu ritmo.'];
 $('#content').innerHTML=title(...heading)+`<div class="filters"><label>Buscar no enunciado ou assunto<input id="search" placeholder="Digite uma palavra-chave" value="${esc(filter.search)}"></label><label>Matéria<select id="subject"><option value="">Todas as matérias</option>${subjects().map(s=>`<option ${s===filter.subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Origem<select id="kind"><option value="">Todas</option><option value="autoral" ${filter.kind==='autoral'?'selected':''}>Autorais</option><option value="prova" ${filter.kind==='prova'?'selected':''}>Provas importadas</option></select></label></div><div id="questionArea"></div>`;
 for(const key of ['search','subject','kind'])$('#'+key).addEventListener(key==='search'?'input':'change',e=>{filter[key]=e.target.value;index=0;answered=false;selection=null;queue=pool();showQuestion()});
 queue=pool();showQuestion();
}
function showQuestion(){
 const area=$('#questionArea');if(!queue.length){area.innerHTML='<div class="card empty"><h2>Nenhuma questão por aqui.</h2><p>Altere os filtros ou comece uma nova sessão de estudo.</p><button id="clearFilters">Limpar filtros</button></div>';$('#clearFilters').onclick=()=>{filter={search:'',subject:'',kind:''};renderPractice()};return}
 index=Math.min(index,queue.length-1);const q=queue[index];area.innerHTML=questionHTML(q,false)+`<div class="actions spaced"><button id="prev" ${index===0?'disabled':''}>← Anterior</button><button id="respond" class="primary" ${selection===null||answered?'disabled':''}>Conferir resposta</button><button id="next" ${index===queue.length-1?'disabled':''}>Próxima →</button><span class="muted">${index+1} de ${queue.length}</span></div>`;
 bindOptions(q,()=>showQuestion());$('#favorite').onclick=()=>{toggleFavorite(q.id);showQuestion()};
 $('#respond').onclick=()=>{if(selection===null||answered)return;answered=true;store.attempts.push({id:q.id,selected:selection,correct:selection===q.answer,at:new Date().toISOString(),mode:'practice'});save();showQuestion()};
 for(const [id,delta] of [['prev',-1],['next',1]])$('#'+id).onclick=()=>{index+=delta;selection=null;answered=false;showQuestion()};
}
function questionHTML(q,exam){return `<article class="card question"><div class="row"><div class="meta">${esc(q.subject)} / ${esc(q.topic)}<br>${q.origin==='autoral'?'AUTORAL • DEMONSTRAÇÃO':esc(q.source.board)+' • '+esc(q.source.year)+' • '+esc(q.source.exam)}</div>${!exam?`<button id="favorite" class="secondary" aria-label="${store.favorites.includes(q.id)?'Remover dos':'Adicionar aos'} favoritos">${store.favorites.includes(q.id)?'★ Salva':'☆ Salvar'}</button>`:''}</div><p class="statement">${esc(q.statement)}</p><div class="options" role="group" aria-label="Alternativas">${q.options.map((o,i)=>`<button class="option ${selection===i?'selected':''} ${answered&&!exam?(i===q.answer?'correct':i===selection?'wrong':''):''}" data-option="${i}" aria-pressed="${selection===i}" ${answered&&!exam?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div>${answered&&!exam?feedback(q,selection):''}</article>`}
function feedback(q,selected){return `<div class="feedback ${selected!==q.answer?'bad':''}" role="status"><b>${selected===q.answer?'Resposta correta!':selected===undefined?'Não respondida.':'Ainda não foi dessa vez.'} Gabarito: ${String.fromCharCode(65+q.answer)}.</b><p>${esc(q.explanation)}</p>${q.origin==='prova'?`<a href="${esc(q.source.examUrl)}" target="_blank" rel="noopener noreferrer">Consultar prova</a> · <a href="${esc(q.source.answerUrl)}" target="_blank" rel="noopener noreferrer">Consultar gabarito</a><p>Fonte informada na importação. Revisão declarada: ${esc(q.source.reviewedAt)}.</p>`:'<small>Questão autoral para demonstração da plataforma.</small>'}</div>`}
function bindOptions(q,fn){document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{selection=Number(b.dataset.option);if(run)run.answers[q.id]=selection;fn()})}
function toggleFavorite(id){store.favorites=store.favorites.includes(id)?store.favorites.filter(x=>x!==id):[...store.favorites,id];save()}
function renderExam(){
 if(run){showExamQuestion();return}
 if(examResult){const r=examResult;$('#content').innerHTML=title('Treino concluído.','Confira o resultado e revise cada resposta.')+`<div class="card"><span class="result-score">${Math.round(r.correct/r.questions.length*100)}%</span><p>${r.correct} de ${r.questions.length} acertos • ${r.unanswered} sem resposta</p><button id="newExam" class="primary">Novo simulado</button></div>`+r.questions.map((q,i)=>`<section class="card spaced"><h3>${i+1}. ${esc(q.statement)}</h3><p class="muted">Sua resposta: ${r.answers[q.id]===undefined?'Não respondida':esc(q.options[r.answers[q.id]])}</p>${feedback(q,r.answers[q.id])}</section>`).join('');$('#newExam').onclick=()=>{examResult=null;renderExam()};return}
 $('#content').innerHTML=title('Simule o dia da prova.','Questões aleatórias, tempo definido por você e correção ao finalizar.')+`<section class="card"><h2>Monte seu treino</h2><div class="filters"><label>Matéria<select id="examSubject"><option value="">Todas as matérias</option>${subjects().map(s=>`<option>${esc(s)}</option>`).join('')}</select></label><label>Quantidade<input id="examCount" type="number" min="1" max="${bank().length}" value="10"></label><label>Tempo em minutos<input id="examTime" type="number" min="1" max="180" value="20"></label></div><p class="muted" id="available"></p><button id="startExam" class="primary">Iniciar simulado →</button><div class="notice">Treino livre. Quantidade, matérias e duração não reproduzem uma prova oficial. Sessão em andamento não é recuperada ao fechar a página.</div></section>`;
 const update=()=>{const n=bank().filter(q=>!$('#examSubject').value||q.subject===$('#examSubject').value).length;$('#examCount').max=n;if(Number($('#examCount').value)>n)$('#examCount').value=n;$('#available').textContent=`${n} questões disponíveis neste recorte.`};$('#examSubject').onchange=update;update();
 $('#startExam').onclick=()=>{const count=Number($('#examCount').value),minutes=Number($('#examTime').value),qs=bank().filter(q=>!$('#examSubject').value||q.subject===$('#examSubject').value);if(!Number.isInteger(count)||count<1||count>qs.length||!Number.isInteger(minutes)||minutes<1||minutes>180){toast('Confira a quantidade e o tempo do simulado.');return}run={questions:shuffle(qs).slice(0,count),answers:Object.create(null),index:0,deadline:Date.now()+minutes*60000};showExamQuestion()};
}
function showExamQuestion(){const q=run.questions[run.index];selection=run.answers[q.id]??null;answered=false;$('#content').innerHTML=`<div class="row"><h1>Simulado em andamento</h1><span class="timer" id="timer"></span></div><p class="muted">Questão ${run.index+1} de ${run.questions.length} • ${Object.keys(run.answers).length} respondidas</p>`+questionHTML(q,true)+`<div class="actions spaced"><button id="examPrev" ${run.index===0?'disabled':''}>← Anterior</button><button id="examNext" ${run.index===run.questions.length-1?'disabled':''}>Próxima →</button><button id="finish" class="primary">Finalizar simulado</button></div>`;bindOptions(q,showExamQuestion);$('#examPrev').onclick=()=>{run.index--;showExamQuestion()};$('#examNext').onclick=()=>{run.index++;showExamQuestion()};$('#finish').onclick=()=>{const missing=run.questions.length-Object.keys(run.answers).length;if(confirm(missing?`Faltam ${missing} respostas. Finalizar mesmo assim?`:'Finalizar e conferir o gabarito?'))finishExam()};tick()}
function tick(){if(!run)return;const secs=Math.max(0,Math.ceil((run.deadline-Date.now())/1000));if($('#timer'))$('#timer').textContent=`${Math.floor(secs/60).toString().padStart(2,'0')}:${(secs%60).toString().padStart(2,'0')}`;if(!secs)finishExam()}
setInterval(tick,1000);
function finishExam(){if(!run)return;const r=run;run=null;const at=new Date().toISOString();let correct=0,unanswered=0;for(const q of r.questions){const selected=r.answers[q.id];if(selected===q.answer)correct++;if(selected===undefined)unanswered++;store.attempts.push({id:q.id,selected:selected??null,correct:selected===q.answer,at,mode:'exam'})}store.sessions.push({at,total:r.questions.length,correct});save();examResult={...r,correct,unanswered};renderExam()}
window.addEventListener('beforeunload',e=>{if(run){e.preventDefault();e.returnValue=''}});
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function renderData(){
 $('#content').innerHTML=title('Seu estudo, seus dados.','O progresso fica salvo neste navegador. Faça backup para levar a outro aparelho.')+`<div class="columns"><section class="card"><h2>Backup do progresso</h2><p class="muted">Inclui respostas, favoritos, simulados e questões importadas. Não há conta nem sincronização na nuvem nesta versão.</p><button id="export" class="primary">Exportar backup</button><label class="spaced">Restaurar backup (.json)<input id="restore" type="file" accept=".json,application/json"></label><p class="muted">A restauração substitui os dados atuais após sua confirmação.</p></section><section class="card"><h2>Adicionar questões</h2><p class="muted">Importe um JSON no formato do projeto. Questões de provas exigem links da prova e do gabarito. A importação é local e não publica para outros usuários.</p><button id="template">Baixar modelo JSON</button><label class="spaced">Importar questões (.json)<input id="import" type="file" accept=".json,application/json"></label><p class="muted">${store.custom.length} questões importadas.</p></section></div><div class="notice">Limpar os dados do navegador pode apagar o progresso. Não armazene senhas ou dados pessoais nos arquivos de questões.</div>`;
 $('#export').onclick=()=>download('pp-mt-backup.json',{version:2,data:store});$('#template').onclick=()=>download('modelo-questoes.json',[{...QUESTIONS[0],id:'minha-questao-001'}]);
 $('#import').onchange=async e=>{try{const list=validateBank(await readFile(e.target.files[0]));const ids=new Set(bank().map(q=>q.id));if(list.some(q=>ids.has(q.id)))throw Error('Já existe uma questão com um dos IDs. Use IDs novos.');if(store.custom.length+list.length>5000)throw Error('Limite local de 5.000 questões importadas.');store.custom.push(...list);save();toast(`${list.length} questões importadas.`);renderData()}catch(err){toast(err.message)}};
 $('#restore').onchange=async e=>{try{const b=await readFile(e.target.files[0]),s=b.data;if(b.version!==2||!s||!Array.isArray(s.attempts)||!Array.isArray(s.favorites)||!Array.isArray(s.sessions))throw Error('Backup inválido.');validateBank(s.custom);const combined=[...QUESTIONS,...s.custom],ids=new Set(combined.map(q=>q.id));if(ids.size!==combined.length)throw Error('IDs repetidos no backup.');if(s.attempts.some(a=>!a||!ids.has(a.id)||typeof a.correct!=='boolean'||!Number.isFinite(Date.parse(a.at))||!(a.selected===null||Number.isInteger(a.selected)&&a.selected>=0&&a.selected<combined.find(q=>q.id===a.id).options.length))||s.favorites.some(id=>!ids.has(id))||s.sessions.some(x=>!x||!Number.isFinite(Date.parse(x.at))||!Number.isInteger(x.total)||x.total<1||!Number.isInteger(x.correct)||x.correct<0||x.correct>x.total))throw Error('O backup contém registros inválidos.');if(confirm('Substituir todo o progresso atual por este backup?')){store={attempts:s.attempts,favorites:[...new Set(s.favorites)],sessions:s.sessions,custom:s.custom};save();toast('Backup restaurado.');renderData()}}catch(err){toast(err.message)}};
}
async function readFile(f){if(!f)throw Error('Selecione um arquivo.');if(f.size>10*1024*1024)throw Error('O arquivo deve ter até 10 MB.');try{return JSON.parse(await f.text())}catch{throw Error('Não foi possível ler o JSON.')}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
navigate();
