// Questões autorais de demonstração. Não foram extraídas de concursos.
const rows = [
['Língua Portuguesa','Concordância','Assinale a frase com concordância verbal adequada.',['Fazem dois anos que estudo.','Faz dois anos que estudo.','Fazem muito tempo que estudo.','Fazem um mês que estudo.'],1,'O verbo fazer, quando indica tempo decorrido, é impessoal e permanece na terceira pessoa do singular.'],
['Língua Portuguesa','Vocabulário','Na expressão “agir consoante as instruções”, consoante significa:',['Contra','Antes de','De acordo com','Apesar de'],2,'Nesse contexto, consoante indica conformidade: de acordo com as instruções.'],
['Língua Portuguesa','Ortografia','Qual palavra está corretamente grafada?',['Excessão','Exceção','Esceção','Exessão'],1,'A grafia correta é exceção.'],
['Língua Portuguesa','Interpretação','“Embora estivesse cansada, a candidata continuou estudando.” A oração inicial expressa:',['Causa','Finalidade','Concessão','Consequência'],2,'Embora introduz uma concessão: o cansaço poderia impedir o estudo, mas isso não aconteceu.'],
['Língua Portuguesa','Crase','Assinale a alternativa em que o uso da crase está correto.',['Começou à estudar.','Entregou o documento à ela.','Voltou à pé.','Dirigiu-se à sala.'],3,'Dirigir-se exige a preposição a. Diante do artigo feminino a de sala, ocorre a fusão: à sala.'],
['Língua Portuguesa','Pontuação','Assinale a frase em que a vírgula separa um vocativo.',['Luan, confira o horário.','Ontem, ele chegou cedo.','Ele estudou, mas não revisou.','Trouxe livros, canetas e papéis.'],0,'Luan é a pessoa chamada diretamente na frase, portanto funciona como vocativo.'],
['Raciocínio Lógico','Porcentagem','Uma candidata acertou 42 de 60 questões. Qual foi seu percentual de acertos?',['60%','65%','70%','75%'],2,'42 ÷ 60 × 100 = 70%.'],
['Raciocínio Lógico','Proporção','Mantendo o mesmo ritmo, uma pessoa resolve 24 questões em 40 minutos. Quantas resolve em 60 minutos?',['30','32','36','40'],2,'24 ÷ 40 × 60 = 36 questões.'],
['Raciocínio Lógico','Sequências','Qual é o próximo número da sequência 3, 6, 12, 24, ...?',['30','36','42','48'],3,'Cada termo é o dobro do anterior: 24 × 2 = 48.'],
['Raciocínio Lógico','Negação','A negação de “Todos os candidatos estudaram” é:',['Nenhum candidato estudou.','Algum candidato não estudou.','Todos os candidatos faltaram.','Algum candidato estudou.'],1,'Para negar uma afirmação universal, basta existir pelo menos uma exceção.'],
['Raciocínio Lógico','Média','As notas de um aluno foram 6, 8 e 10. Qual é a média aritmética?',['7','8','9','24'],1,'A soma é 24. Dividindo pelas três notas, temos 8.'],
['Raciocínio Lógico','Probabilidade','Em uma caixa há 3 fichas azuis e 2 vermelhas. Ao retirar uma ficha ao acaso, a probabilidade de sair vermelha é:',['20%','30%','40%','60%'],2,'São 2 resultados favoráveis entre 5 possíveis: 2/5 = 40%.'],
['Informática','Segurança','Qual atitude ajuda a proteger uma conta contra acesso indevido?',['Reutilizar a senha do e-mail.','Compartilhar códigos de acesso.','Ativar autenticação em dois fatores.','Desativar atualizações.'],2,'A autenticação em dois fatores adiciona uma verificação além da senha.'],
['Informática','Phishing','Um e-mail solicita sua senha e cria urgência para clicar em um link suspeito. Qual é a atitude mais adequada?',['Enviar a senha por resposta.','Verificar a solicitação por um canal oficial independente.','Abrir todos os anexos.','Encaminhar o código de autenticação.'],1,'Verifique a solicitação por um canal oficial obtido de forma independente, sem confiar no link recebido.'],
['Informática','Backup','Qual é a finalidade principal de um backup?',['Aumentar a resolução da tela.','Eliminar a necessidade de senha.','Permitir recuperar dados em caso de perda.','Acelerar qualquer conexão.'],2,'Backup é uma cópia de segurança que permite a recuperação de dados.'],
['Informática','Planilhas','Em uma planilha, a fórmula =SOMA(A1:A3) calcula:',['Apenas A1 + A3.','A soma de A1, A2 e A3.','A média de A1 e A3.','A quantidade de letras em A1.'],1,'O intervalo A1:A3 inclui as células A1, A2 e A3.'],
['Informática','Navegação','O protocolo HTTPS oferece principalmente:',['Garantia de que toda notícia é verdadeira.','Proteção criptográfica dos dados em trânsito entre navegador e servidor.','Eliminação de todos os vírus.','Anonimato absoluto.'],1,'HTTPS protege a comunicação em trânsito. Sua presença não garante a honestidade do conteúdo do site.'],
['Informática','Arquivos','Qual extensão é normalmente associada a um documento PDF?',['.jpg','.mp3','.pdf','.csv'],2,'A extensão .pdf identifica normalmente um arquivo Portable Document Format.']
];
export const QUESTIONS = rows.map((r,i)=>({id:`demo-${String(i+1).padStart(3,'0')}`,subject:r[0],topic:r[1],statement:r[2],options:r[3],answer:r[4],explanation:r[5],origin:'autoral',source:null}));
