import {MT_QUESTIONS} from './official.js?v=27';
// Exercises derived from the cited MT lessons; AI-assisted editorial content.
// They are not official questions and have not received independent teacher review.
const CASES={
1:['Um texto diz: “Rafael tremia, embora a sala estivesse quente”. Qual leitura permanece apoiada no texto?','O tremor não pode ser explicado automaticamente pelo frio da sala.','Rafael tinha necessariamente uma doença.','A sala estava fria.','O texto afasta o frio da sala como explicação automática; não prova uma doença.'],
2:['“Foi a viagem mais longa que já fiz.” A avaliação de duração está limitada a quê?','À experiência pessoal de quem fala.','A todas as viagens já realizadas por qualquer pessoa.','A uma medição universal comprovada.','“Que já fiz” restringe a comparação ao repertório do falante.'],
3:['Em “Os relatórios que chegaram foram arquivados”, o termo “que” funciona como:','Pronome relativo que retoma relatórios.','Conjunção integrante sem antecedente.','Preposição que introduz finalidade.','O termo retoma relatórios e exerce função dentro da oração.'],
4:['Em “Os candidatos que estudaram foram aprovados”, a oração destacada por “que” serve para:','Restringir quais candidatos são mencionados.','Indicar o horário da aprovação.','Apresentar a causa de todos os candidatos terem passado.','A oração caracteriza e restringe o antecedente candidatos.'],
5:['Em “A notícia acendeu uma esperança”, o verbo acender foi empregado em sentido:','Figurado, relacionado ao surgimento de esperança.','Literal, indicando uma chama física.','Literal, indicando um defeito elétrico.','Esperança não é objeto que se incendeia; a expressão transfere o sentido.'],
6:['Uma pessoa aponta para a cadeira e diz “Sente aqui”. Para localizar “aqui”, é preciso:','Conhecer a situação e o lugar de quem fala.','Procurar obrigatoriamente um substantivo anterior no texto.','Consultar apenas o dicionário.','Aqui é referência espacial ancorada na enunciação.'],
7:['Sem mudar quem foi visto, como substituir “Eu vi a candidata” por pronome?','Eu a vi.','Eu te vi.','Eu me vi.','A retoma a candidata; te muda a referência para o interlocutor e me para o falante.'],
8:['Em “O agente continuou calmo”, qual é a função de “calmo”?','Predicativo do sujeito.','Sujeito da oração.','Objeto direto de continuou.','Calmo atribui um estado ao sujeito por meio do predicado.'],
9:['Qual frase emprega corretamente haver no sentido de existir?','Havia muitas dúvidas na turma.','Haviam muitas dúvidas na turma.','Houveram muitas dúvidas na turma.','Haver existencial é impessoal e permanece no singular.'],
10:['“Revisou o assunto para compreender a regra.” O trecho iniciado por “para” expressa:','Finalidade.','Uma consequência já ocorrida.','Uma oposição.','Compreender a regra é o objetivo da revisão.'],
12:['Para montar uma linha do tempo de Dante de Oliveira, qual par corresponde às eleições de 1994 e 1998?','PDT em 1994; PSDB em 1998.','PSDB em 1994; PDT em 1998.','PDT nas duas eleições.','A linha do tempo distingue eleição de 1994 pelo PDT e reeleição de 1998 pelo PSDB.'],
13:['Ao comparar os grupos da Rusga, qual associação é adequada ao conteúdo estudado?','Zelosos: campo liberal; Filantrópica: conservador/restaurador.','Zelosos: campo restaurador; Filantrópica: liberal.','Os dois grupos tinham identidade política necessariamente igual.','A oposição entre os grupos ajuda a compreender a disputa política regencial.'],
14:['Um atendimento começa às 14h em MT (UTC−4). Qual horário corresponde no DF (UTC−3), considerando esses fusos?','15h.','13h.','14h.','UTC−3 está uma hora à frente de UTC−4.'],
15:['Em um mapa de MT, qual par de bacias deve ser associado à Serra do Roncador?','Araguaia e Xingu.','Paraná e São Francisco.','Uruguai e Paraíba do Sul.','A associação geográfica estudada é Araguaia–Xingu.'],
17:['Um aluno procura o autor de Mênon e Eutífron. Qual autor deve selecionar?','Platão.','Kant.','Descartes.','Esses diálogos são associados a Platão.'],
18:['Uma teoria destaca a experiência como fundamento do conhecimento. Qual orientação ela exemplifica?','Empirismo.','Racionalismo como primazia da razão.','Uma posição que necessariamente dispensa qualquer experiência.','O contraste central estudado é experiência no empirismo e razão no racionalismo.'],
20:['Uma pessoa pergunta se deve cumprir um dever mesmo quando isso é inconveniente. Qual questão kantiana se aproxima desse problema?','O que devo fazer?','O que posso conhecer?','Qual objeto ocupa mais espaço?','O problema da ação e do dever corresponde à razão prática.'],
21:['O Estado cria um procedimento para permitir a proteção de um direito. Essa atuação representa:','Prestação jurídica ou organizacional.','Apenas abstenção estatal.','Necessariamente entrega de um bem material.','Criar regras e procedimentos é prestação jurídica/organizacional.'],
23:['Uma pessoa de 17 anos pergunta se seu voto é obrigatório. Qual resposta corresponde à regra constitucional estudada?','O voto é facultativo nessa faixa etária.','O voto é obrigatório para qualquer pessoa acima de 16 anos.','O sufrágio universal elimina o voto facultativo.','A universalidade do sufrágio convive com voto facultativo para maiores de 16 e menores de 18.'],
26:['Um herdeiro recebeu patrimônio de R$ 20 mil. Ao discutir reparação de dano imputada ao falecido, qual limite patrimonial importa?','O patrimônio transferido ao sucessor.','Todo o patrimônio próprio do herdeiro, sem limite.','O fato de herdar elimina qualquer possibilidade de reparação.','A obrigação pode alcançar sucessores até o limite do patrimônio recebido.'],
27:['Uma família solicita vaga em creche para uma criança de 2 anos. A ausência de matrícula obrigatória nessa idade significa que não há direito à educação infantil?','Não; educação infantil e matrícula obrigatória têm faixas distintas.','Sim; nenhum direito educacional existe antes dos 4 anos.','Sim; educação infantil começa aos 6 anos.','Educação infantil alcança até 5 anos; a educação básica obrigatória vai de 4 a 17.'],
28:['Uma pessoa sem formação jurídica pretende impetrar HC em favor de um familiar. A falta de advogado impede a impetração?','Não; HC dispensa capacidade postulatória técnica.','Sim; somente advogado pode impetrar HC.','Sim; somente o próprio preso pode pedir HC.','A impetração de HC não exige advogado.'],
29:['Uma unidade estima aumento de demanda e decide ampliar a equipe no mês seguinte. A decisão de ampliar a equipe representa:','Planejamento de ações futuras.','Somente previsão, sem definição de ação.','Uma descrição exclusiva do passado.','Estimar a demanda é prever; organizar a resposta futura é planejar.'],
31:['Há uma fila grande no atendimento. Antes de contratar funcionários, qual passo melhora a decisão?','Diagnosticar se a causa é falta de pessoal, sistema lento ou outro problema.','Escolher imediatamente a solução mais cara.','Ignorar as causas e repetir a última solução.','Diagnosticar evita atuar apenas no sintoma e permite comparar alternativas.'],
32:['Uma equipe acompanha a adoção de uma tecnologia ao longo dos meses. Qual etapa da análise ambiental está realizando?','Monitoramento.','Previsão de acontecimentos futuros.','Avaliação final de impactos apenas.','Acompanhar a evolução é monitorar; projetar é prever; julgar relevância é avaliar.'],
33:['Uma organização prepara planos para demanda alta, média e baixa. O uso desses cenários pretende:','Testar decisões em futuros plausíveis.','Garantir que um futuro previsto acontecerá.','Eliminar totalmente a incerteza.','Cenários ajudam a preparar respostas; não são garantias do futuro.'],
35:['Uma licença foi concedida sem um requisito exigido em lei. Qual instrumento corresponde à ilegalidade?','Anulação.','Revogação apenas por conveniência.','Manutenção obrigatória por já ter sido concedida.','Ilegalidade aponta para anulação; revogação se relaciona ao mérito de ato válido.'],
36:['A fiscalização sanitária exige condições de higiene de um restaurante. Isso pode representar:','Exercício de polícia administrativa por órgão competente.','Investigação criminal obrigatória.','Atividade que somente policial armado pode exercer.','Polícia administrativa limita atividades em favor do interesse público e não se restringe a policiais.'],
37:['Em responsabilidade objetiva do Estado, a dispensa de provar culpa significa que a vítima pode dispensar dano e nexo causal?','Não; dano e nexo continuam necessários.','Sim; basta alegar qualquer prejuízo.','Sim; não existe requisito além da culpa.','Responsabilidade objetiva dispensa culpa, mas não os demais pressupostos.'],
38:['Uma autorização era válida, mas o beneficiário passou a descumprir suas condições. Qual forma de retirada se relaciona ao caso?','Cassação.','Anulação por vício existente necessariamente na origem.','Revogação obrigatória por qualquer ilegalidade inicial.','A cassação decorre do descumprimento posterior das condições pelo beneficiário.'],
39:['Ao estruturar uma sociedade de economia mista, qual forma societária deve ser adotada?','Sociedade anônima.','Associação civil sem participação acionária.','Autarquia.','Sociedade de economia mista deve adotar a forma de sociedade anônima.'],
40:['Uma prefeitura proíbe nova padaria apenas para proteger a já instalada da concorrência. Qual avaliação corresponde ao conceito estudado?','A proteção isolada do concorrente não é fundamento público legítimo para essa restrição.','A concorrência pode sempre ser proibida para favorecer o comerciante antigo.','Toda padaria nova precisa ser impedida por polícia administrativa.','Poder de polícia exige fundamento público legítimo; não autoriza reserva comercial por si só.'],
42:['Uma norma exige estrutura para amamentação “no mínimo até 6 meses”. Qual interpretação preserva o sentido de mínimo?','O prazo é um piso, não um teto de seis meses.','O atendimento deve terminar obrigatoriamente antes de seis meses.','Mínimo e máximo têm o mesmo sentido.','Trocar mínimo por máximo inverte o limite da garantia.'],
43:['Quem tinha dever de evitar ou apurar tortura se omite. A modalidade omissiva estudada tem:','Pena própria prevista no art. 1º, §2º, da lei de tortura.','Automaticamente a mesma pena de qualquer modalidade principal.','Ausência automática de consequência penal.','A modalidade omissiva prevê pena própria de detenção de 1 a 4 anos.'],
44:['Um condenado cumprirá pena em regime semiaberto. Qual estabelecimento se associa a esse regime?','Colônia agrícola, industrial ou similar.','Cadeia pública como destinação própria de todo condenado.','Penitenciária como estabelecimento próprio do semiaberto.','A LEP associa colônia agrícola, industrial ou similar ao regime semiaberto.'],
45:['Durante uma prisão, o agente quer usar algemas apenas para exibir o preso. Qual avaliação corresponde à orientação estudada?','A exibição, por si só, não justifica algemas; a excepcionalidade exige justificativa nas hipóteses previstas.','Toda prisão autoriza algemas automaticamente.','A justificativa escrita é sempre dispensada.','O uso excepcional se relaciona a resistência ou risco de fuga ou à integridade física e exige justificativa escrita.'],
46:['Uma alternativa limita a hipótese do CPP para mulher com filho a crianças menores de 10 anos. Qual problema existe nessa formulação?','Ela restringe a faixa legal de até 12 anos incompletos.','Ela amplia a faixa legal para além de 12 anos.','Ela reproduz exatamente a faixa do inciso V.','A faixa do inciso V é até 12 anos incompletos; o preenchimento da idade não dispensa examinar as condições legais do caso.'],
47:['Uma pessoa acusada de crime hediondo alega coação ilegal. A natureza do crime impede, por si só, o HC?','Não; a garantia contra coação ilegal continua aplicável.','Sim; HC inexiste para qualquer crime hediondo.','Sim; gravidade substitui a análise da legalidade.','A gravidade da acusação não elimina a proteção por HC contra coação ilegal.'],
48:['Uma prova posterior foi obtida por fonte independente. No exame da ilicitude por derivação, essa circunstância:','Precisa ser analisada, pois o CPP prevê limites à contaminação por derivação.','É irrelevante, pois toda prova posterior é necessariamente ilícita.','Torna qualquer prova anterior lícita automaticamente.','O art. 157 prevê falta de nexo causal e fonte independente como limites, nos termos legais.'],
49:['Uma linha do tempo marca a proclamação da DUDH. Qual ano deve constar?','1948.','1988.','2004.','A DUDH foi proclamada em 1948.'],
50:['Um Estado aboliu a pena de morte e pretende restabelecê-la. Segundo a regra estudada da Convenção Americana:','O restabelecimento é vedado pelo art. 4.3.','A abolição autoriza recriação sem limite convencional.','A vedação depende apenas do nome dado à pena.','A Convenção impede restabelecer a pena de morte nos Estados que a aboliram.'],
52:['Uma pessoa foi condenada criminalmente. Qual afirmação corresponde à universalidade dos direitos humanos?','Ela continua titular de direitos humanos, com as restrições legais específicas.','Ela perde automaticamente todos os direitos humanos.','A titularidade depende de nunca ter recebido condenação.','A universalidade inclui pessoas condenadas; isso convive com restrições legais.'],
53:['Há notícia de violação de direitos humanos, mas a vítima não fez pedido ao CNDH. Isso impede necessariamente a atuação do conselho?','Não; a lei permite atuação independentemente de provocação.','Sim; sempre é necessário pedido pessoal da vítima.','Sim; o conselho só atua em disputas eleitorais.','O CNDH pode atuar independentemente de provocação, dentro de suas atribuições.'],
54:['Um estrangeiro pede reconhecimento administrativo de refúgio em primeira instância. Qual órgão tem essa competência estudada?','CONARE.','Qualquer órgão que receba o estrangeiro.','CNDH como substituto automático do CONARE.','O reconhecimento administrativo em primeira instância é atribuição do CONARE.'],
55:['A falta de regulamentação torna inviável o exercício de um direito constitucional. Qual instrumento se relaciona a essa omissão?','Mandado de injunção.','Uma ação destinada exclusivamente a discutir qualquer lei desagradável.','Um recurso criminal obrigatório.','O mandado de injunção se relaciona à omissão regulamentadora que inviabiliza o exercício protegido.'],
57:['Logo após um roubo, inicia-se perseguição nas condições que façam presumir ser o perseguido autor. Qual espécie de flagrante corresponde?','Flagrante impróprio.','Flagrante presumido apenas por encontro posterior com objetos.','Ausência necessária de flagrante porque houve perseguição.','A perseguição logo após, nas condições do art. 302, III, caracteriza flagrante impróprio.'],
58:['Um servidor retarda indevidamente ato de ofício para satisfazer sentimento pessoal. Qual figura corresponde a essa motivação?','Prevaricação.','Corrupção passiva privilegiada caracterizada apenas por pedido de outrem.','Uma decisão necessariamente lícita por motivação pessoal.','Interesse ou sentimento pessoal diferencia prevaricação da modalidade privilegiada ligada a pedido ou influência.'],
60:['Um agente recebe vantagem econômica indevida para facilitar venda de bem público abaixo do mercado. Qual elemento aponta para enriquecimento ilícito?','O benefício econômico indevido recebido pelo agente, com análise do dolo exigido.','A simples diferença de preço, sem examinar vantagem nem dolo.','Qualquer irregularidade contábil sem elemento subjetivo.','A vantagem pessoal indevida distingue o caso; a configuração atual exige dolo.']
};
export const CONCEPT_PRACTICE=MT_QUESTIONS.filter(q=>CASES[q.source.number]&&!q.historicalOnly).map(q=>{
 const [statement,...parts]=CASES[q.source.number],explanation=parts.pop();
 const shift=Number(q.source.number)%3,options=parts.slice(shift).concat(parts.slice(0,shift)),answer=(3-shift)%3;
 return {id:`concept-practice:${q.id}`,subject:q.subject,topic:q.topic,conceptId:q.id,baseId:q.id,origin:'autoral',practiceKind:'application',statement,options,answer,explanation,
 lesson:{...q.lesson,reasoning:explanation,alternatives:options.map((o,i)=>i===answer?explanation:'Esta opção contraria a distinção explicada no conceito. '+explanation),authorship:'Exercício autoral com assistência de IA, derivado das fontes do comentário-base. Não é questão oficial nem revisão docente independente.'}};
});
