import test from 'node:test';
import assert from 'node:assert/strict';
import {QUESTIONS} from '../data.js';
import {validateBank,summary,latestErrors,shuffle} from '../core.js';
test('banco demonstrativo é válido e não atribui banca ou concurso falso',()=>{assert.equal(validateBank(QUESTIONS).length,18);assert.ok(QUESTIONS.every(q=>q.origin==='autoral'&&q.source===null))});
test('gabarito fora das alternativas é recusado',()=>assert.throws(()=>validateBank([{...QUESTIONS[0],answer:8}])));
test('IDs duplicados são recusados',()=>assert.throws(()=>validateBank([QUESTIONS[0],QUESTIONS[0]])));
test('prova sem origem documentada é recusada',()=>assert.throws(()=>validateBank([{...QUESTIONS[0],origin:'prova'}])));
test('links executáveis de fonte são recusados',()=>assert.throws(()=>validateBank([{...QUESTIONS[0],origin:'prova',source:{board:'B',exam:'E',year:'2020',number:'1',examUrl:'javascript:alert(1)',answerUrl:'https://example.com',reviewedAt:'2026-10-07'}}])));
test('erro revisado com acerto sai do caderno de erros',()=>{const a=[{id:'a',correct:false},{id:'b',correct:false},{id:'a',correct:true}];assert.deepEqual([...latestErrors(a)],['b']);assert.deepEqual(summary(a),{total:3,correct:1,rate:33})});
test('embaralhamento não perde ou duplica questões',()=>{const r=shuffle(QUESTIONS);assert.notEqual(r,QUESTIONS);assert.deepEqual(r.map(q=>q.id).sort(),QUESTIONS.map(q=>q.id).sort())});
import {MT_QUESTIONS as OFFICIAL_QUESTIONS,MT_EXAM} from '../official.js';
test('prova de MT contém exatamente as 57 questões válidas, sem anuladas',()=>{validateBank(OFFICIAL_QUESTIONS);assert.equal(OFFICIAL_QUESTIONS.length,57);assert.deepEqual(MT_EXAM.annulled,[16,41,56]);const numbers=OFFICIAL_QUESTIONS.map(q=>Number(q.source.number));assert.deepEqual(numbers,Array.from({length:60},(_,i)=>i+1).filter(n=>![16,41,56].includes(n)));validateBank([...QUESTIONS,...OFFICIAL_QUESTIONS]);});
test('respostas correspondem ao gabarito final S05 T, página 13',()=>{const key='E A B D A B E E C D E E A A E * E E A C C D E B C A C B A C E C E C E A D A B B * D A B A C E D E A E E C D C * B E D C'.split(' ');for(const q of OFFICIAL_QUESTIONS){assert.equal(String.fromCharCode(65+q.answer),key[Number(q.source.number)-1]);assert.equal(q.source.code,'S05');assert.equal(q.source.version,'T');assert.equal(q.source.answerPage,13);assert.ok(q.source.examUrl.endsWith('/S05-T.pdf'));}});
test('questões oficiais estão transcritas no app com fonte preservada',()=>{for(const q of OFFICIAL_QUESTIONS){assert.equal(q.displayMode,'inline');assert.ok(Number.isInteger(q.source.page)&&q.source.page>=2&&q.source.page<=17);assert.equal(q.origin,'prova');assert.ok(typeof q.statement==='string'&&q.statement.length>10);assert.equal(q.options.length,5);assert.ok(q.options.every(o=>typeof o==='string'&&o.trim().length>0));assert.ok(!q.options.some(o=>/^Alternativa [A-E]$/.test(o)));}assert.equal(OFFICIAL_QUESTIONS.at(-1).source.page,17);});
