import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8');
test('V 2.19.6 não mostra cronômetro no cabeçalho mobile e preserva opções de conta',()=>{
 const page=read('index.html'),app=read('app.js'),css=read('style.css');
 assert.doesNotMatch(page,/id="studyClockMini"/);
 assert.doesNotMatch(app,/studyClockMini/);
 assert.match(app,/notificationBell/);
 assert.match(app,/Administração/);
 assert.match(app,/id="logout"/);
 assert.match(app,/studyClockToggle/);
 assert.match(app,/data-study-time/);
 assert.match(css,/\.main>header\{display:flex;flex-wrap:nowrap/);
 assert.match(css,/\.main>header \.header-right\{display:flex;align-items:center/);
 assert.match(css,/\.main>header \.admin-label\{display:none\}/);
 assert.match(page,/app\.js\?v=2\.19\.6/);
 assert.match(page,/style\.css\?v=2\.19\.6/);
 assert.match(app,/const APP_VERSION='2\.19\.6'/);
 assert.match(read('sw.js'),/const CACHE='ppmt-2\.19\.6-header-align'/);
});
