"""Compile the editable, syllabus-linked authorial batch to a static browser module."""
import json
from pathlib import Path
root=Path(__file__).resolve().parent.parent
files=[root/'content/authorial-mt-100.json',*sorted((root/'content').glob('authorial-mt-*-lote*.json'))]
corpora=[json.loads(p.read_text()) for p in files]
sources=json.loads((root/'content/lesson-sources.json').read_text())
questions=[]
for corpus in corpora:
    before=len(questions)
    for g in corpus['groups']:
        base='mt-autoral-202610-'+g['slug']+'-01'
        for i,e in enumerate(g['exercises']):
            # Stable editorial ordering, balanced answer positions; comments move with options.
            shift=(len(questions)-before)%len(e['options'])
            order=list(range(len(e['options'])))
            order=order[shift:]+order[:shift]
            answer=order.index(e['answer'])
            lesson={'concept':g['concept'],'reasoning':e['reasons'][e['answer']],
                    'alternatives':[e['reasons'][j] for j in order],
                    'example':g['example'],'recall':g['recall'],'note':corpus['syllabus']['note'],
                    'status':'explained','checkedAt':corpus['checkedAt'],'authorship':corpus['authorship'],
                    'sources':[sources[k] for k in g['sourceKeys']]+[{'title':corpus['syllabus']['title'],'url':corpus['syllabus']['url']}]}
            questions.append({'id':base[:-2]+f'{i+1:02d}','subject':g['subject'],'topic':g['title'],
                              'conceptId':base,'baseId':base,'origin':'autoral','practiceKind':'application',
                              'edition':corpus['edition'],'syllabusTopic':g['syllabusTopic'],
                              'statement':e['statement'],'options':[e['options'][j] for j in order],
                              'answer':answer,'explanation':lesson['reasoning'],'lesson':lesson})
    assert len(questions)-before==corpus.get('expectedCount',100),corpus['edition']
assert len(questions)==sum(c.get('expectedCount',100) for c in corpora)
assert len({q['id'] for q in questions})==len(questions)
assert len({q['statement'] for q in questions})==len(questions)
out='// Generated by tools/build_authorial.py; edit content/authorial-mt-*.json.\n'
out+='export const AUTHORIAL_MT_QUESTIONS='+json.dumps(questions,ensure_ascii=False,separators=(',',':'))+';\n'
out+="export const AUTHORIAL_MT_CONCEPTS=AUTHORIAL_MT_QUESTIONS.filter(q=>q.id===q.conceptId).map(q=>({id:q.id,title:q.topic,subject:q.subject,lesson:q.lesson,baseId:q.id}));\n"
(root/'authorial-mt.js').write_text(out)
