"""Compile the editable lesson corpus into a static browser module, no runtime fetch."""
import json
from pathlib import Path
root=Path(__file__).resolve().parent.parent
lessons=json.loads((root/'content/mt-2017-lessons.json').read_text())
sources=json.loads((root/'content/lesson-sources.json').read_text())
for key,lesson in lessons.items():
    lesson['sourceKeys']=list(dict.fromkeys(lesson['sourceKeys']+['key']))
    lesson['sources']=[sources[k] for k in lesson.pop('sourceKeys')]
    assert len(lesson['alternatives'])==5,key
out='// Generated by tools/build_lessons.py; edit content/mt-2017-lessons.json.\n'
out+='export const MT_LESSONS='+json.dumps(lessons,ensure_ascii=False,separators=(',',':'))+';\n'
out+='export function enrichMTQuestion(q){const lesson=MT_LESSONS[q.id];return lesson?{...q,topic:lesson.topic,explanation:lesson.reasoning,lesson,historicalOnly:lesson.status==="historical-only"}:q}\n'
(root/'lessons.js').write_text(out)
